
project_id = "vrtorxjtxvrqxdsfrywo"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[realtime]
enabled = false

# Edge Functions
[functions.job-match-analysis]
verify_jwt = true

[functions.generate-application]
verify_jwt = true

[functions.simulate-conversation]
verify_jwt = true

[functions.update-learning-profile]
verify_jwt = true

[functions.interview-simulation]
verify_jwt = true
