-- Insert real candidate data
INSERT INTO public.candidate_profiles (first_name, last_name, email, bio, skills, experience_years, location, avatar_color, resume_url) VALUES 
('Jennifer', 'Adams', 'jennifer.adams@email.com', 'UX/UI Designer avec 5 ans d''expérience spécialisée en design d''interface utilisateur et recherche utilisateur. Passionnée par la création d''expériences utilisateur intuitives et accessibles.', ARRAY['Figma', 'Adobe XD', 'Sketch', 'UI Design', 'User Research'], 5, 'London, UK', 'bg-purple-500', 'https://drive.google.com/file/d/jennifer-adams-cv'),

('Michael', 'Johnson', 'michael.johnson@email.com', 'Développeur Full Stack avec 7 ans d''expérience en React, Node.js et TypeScript. Expert en architecture cloud AWS et pratiques DevOps.', ARRAY['React', 'Node.js', 'TypeScript', 'MongoDB', 'AWS'], 7, 'New York, USA', 'bg-blue-500', 'https://drive.google.com/file/d/michael-johnson-cv'),

('Emma', 'Wilson', 'emma.wilson@email.com', 'Spécialiste Marketing Digital avec 4 ans d''expérience en SEO, stratégie de contenu et campagnes PPC. Passionnée par l''analyse de données et l''optimisation de conversion.', ARRAY['SEO', 'Content Strategy', 'Social Media', 'Google Analytics', 'PPC'], 4, 'Berlin, Germany', 'bg-red-500', 'https://drive.google.com/file/d/emma-wilson-cv'),

('David', 'Chen', 'david.chen@email.com', 'Product Manager avec 8 ans d''expérience en stratégie produit et méthodologies Agile. Expert en recherche utilisateur et analyse de données pour optimiser les produits.', ARRAY['Product Strategy', 'Agile', 'User Research', 'Data Analysis', 'Roadmapping'], 8, 'San Francisco, USA', 'bg-green-500', 'https://drive.google.com/file/d/david-chen-cv'),

('Sarah', 'Parker', 'sarah.parker@email.com', 'Graphiste créative avec 6 ans d''expérience en branding, typographie et illustration. Maîtrise complète de la suite Adobe Creative et passion pour le design print.', ARRAY['Adobe Creative Suite', 'Branding', 'Typography', 'Illustration', 'Print Design'], 6, 'Melbourne, Australia', 'bg-yellow-500', 'https://drive.google.com/file/d/sarah-parker-cv'),

('James', 'Wilson', 'james.wilson@email.com', 'Data Scientist avec 5 ans d''expérience en Python, Machine Learning et visualisation de données. Spécialisé dans l''analyse prédictive et les modèles statistiques.', ARRAY['Python', 'Machine Learning', 'SQL', 'Data Visualization', 'Statistics'], 5, 'Toronto, Canada', 'bg-indigo-500', 'https://drive.google.com/file/d/james-wilson-cv'),

('Olivia', 'Martinez', 'olivia.martinez@email.com', 'Rédactrice de contenu avec 3 ans d''expérience en copywriting, blogging et rédaction SEO. Passionnée par la création de contenu engageant et optimisé.', ARRAY['Copywriting', 'Blogging', 'SEO Writing', 'Editing', 'Research'], 3, 'Madrid, Spain', 'bg-pink-500', 'https://drive.google.com/file/d/olivia-martinez-cv'),

('Thomas', 'Wright', 'thomas.wright@email.com', 'Développeur Frontend avec 4 ans d''expérience en HTML/CSS, JavaScript et React. Spécialisé dans le design responsive et l''optimisation de performance.', ARRAY['HTML/CSS', 'JavaScript', 'React', 'Vue.js', 'Responsive Design'], 4, 'Paris, France', 'bg-cyan-500', 'https://drive.google.com/file/d/thomas-wright-cv');