// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrtorxjtxvrqxdsfrywo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydG9yeGp0eHZycXhkc2ZyeXdvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkwOTc1MDgsImV4cCI6MjA1NDY3MzUwOH0.FvtiosDosFOPiwBeJ_T3Iw2NFv2d_Bzxp3237htQnzM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);